#!/bin/bash
#
################################################################################
#
#@author    Marco Israel (MI)
#@date      2020-02
#@authors   Last changed by:  Marco Israel - 2020.
#
#
#@brief     Builds the databases for ctag and cscope
#@details   Should be called from the projects root location. The script
#           creates there a (hidden) folder an places there the scope files
#           generated by ctags and cscope which will be called by this script.
#
#@attention Note you have to configure your editor /IDE to use this files inside
#           folder mentioned in bevor. E.g you have to 'set tags' and 'cs add'
#           in your .vimrc or after involving vim if this is your editor.
#
#
################################################################################

if [ "$#" -gt 1 ]
then
    echo "#####################################################################"
    echo ""
    echo "NOTE: You do NOT need to pas any arguments to this script):"
    echo "USAGE: "
    echo "${0##*/} [<your-scopefolder]"
    echo ""
    echo "#####################################################################"
fi



# Define defaults
SCOPE_FILE="scopefiles"

if [ $1 ]
then
    SCOPE_DIR="$1"
else
    SCOPE_DIR="$PWD/.scopedb"
fi



if [ ! -d "$SCOPE_DIR" ]; then
mkdir "$SCOPE_DIR"
fi



# Generate scope filelist
echo "Finding files ..."
find "$PWD" -name '*.[ch]' \
-o -name '*.java' \
-o -name '*properties' \
-o -name '*.cpp' \
-o -name '*.cc' \
-o -name '*.hpp' \
-o -name '*.py' \
-o -name '*.mk' \
-o -name '*.make' \
-o -name '*.tex' \
-o -name '*.php' > "$SCOPE_DIR/$SCOPE_FILE"



# Generate cscope database
cscope -b -i "$SCOPE_DIR/$SCOPE_FILE"



# Generate ctags database
ctags --recurse=n -L "$SCOPE_DIR/$SCOPE_FILE"



# Cleanup and exit
mv cscope.out $SCOPE_DIR/cscope.db
mv tags $SCOPE_DIR/ctags.db

echo "Finished building scops"

##### EOF ######################################################################
